### ISSUE TITLE
how to reproduce the siglip's performance on MMVP-VLM Benchmark?

### ISSUE THREAD

**Issue by Rubics-Xuan** [tsb0601/MMVP#20]
Many thanks for your great work! I have a question that how to reproduce the siglip's performance on MMVP-VLM Benchmark?

**Comment by nahidalam** [comment]
@Rubics-Xuan how did you resolve it? The code https://github.com/tsb0601/MMVP/blob/main/scripts/evaluate_vlm.py seems to be hardcoded to OpenAI clip models. Trying to do a generic implementation here `https://github.com/nahidalam/MMVP/blob/dev/scripts/evaluate_any_vlm.py` but getting all `0` for the results here https://github.com/tsb0601/MMVP/blob/main/imgs/vlm_results.png
