### ISSUE TITLE
How to evaluate the DFN model? 

### ISSUE THREAD

**Issue by DesertsP** [tsb0601/MMVP#4]
Where the weights and codes can be found?

**Comment by tsb0601** [comment]
Hi, 

The weight for DFN can be found in huggingface (for example, https://huggingface.co/apple/DFN2B-CLIP-ViT-L-14). Please use adapt from [evaluate_vlm.py](https://github.com/tsb0601/MMVP/blob/main/scripts/evaluate_vlm.py) to evaluate DFN and other models. We'll also add a script that includes downloading the models weight.
