### ISSUE TITLE
leaked api key

### ISSUE THREAD

**Issue by lucasrodes** [tsb0601/MMVP#7]
hi, i just popped by to say that you may have a leak of your OPENAI API key token. I suggest deleting it, unless you've already have done that.

https://github.com/tsb0601/MMVP/blob/763500597e65c3446f09047837ceda76f4e264bf/LLaVA/scripts/v1_5/eval/llavabench.sh#L13

**Comment by tsb0601** [comment]
Thank you so much!!! We will remove it.
